openapi: 3.1.0
info:
  title: Online Bookstore
  version: 1.3.0
  description: Online Bookstore API
servers:
  - url: http://localhost:8000
    description: Local server
tags:
  - name: Auth
    description: Authentication management
  - name: Account
    description: Account management
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT